Fixed `TypeError` when `asdict` is called for classes that have a `namedtuple` field with parameter `retain_collection_types=True`.
